### ISSUE TITLE
[EN] missing translation /pathfinding-magical-numbers

### ISSUE THREAD

**Issue by pagoru** [voidpixel/apiblog.voidpixel.net#2]
https://github.com/voidpixel/apiblog.voidpixel.net/blob/master/src/posts/pathfinding-magical-numbers/en.md

Spanish ref: https://github.com/voidpixel/apiblog.voidpixel.net/blob/master/src/posts/pathfinding-magical-numbers/es.md

**Comment by peoplenarthax** [comment]
https://github.com/voidpixel/apiblog.voidpixel.net/pull/4 Adds the missing translation
